version: "3.7"


services:
  app: 
    image: meu-servidor-web7
    ports:
      - 89:80
    working_dir: /app
    volumes:
      - ./index.php:/var/www/html/index.php
    environment:     
    -  MYSQL_HOST=${MYSQL_HOST}
    -  MYSQL_USER=${MYSQL_USER}
    -  MYSQL_PASSWORD=${MYSQL_PASSWORD}
    -  MYSQL_DB=${MYSQL_DB}

  mysql:
    image: mysql:latest
    ports:
      - 3333:3306
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}

volumes:
  todo-mysql-data:


  