FROM nginx:latest

COPY Interface Web/index.html /usr/share/nginx/html/
COPY Interface Web/criarEvento.html /usr/share/nginx/html/
#COPY pesquisarEvento.html /usr/share/nginx/html/
#COPY submit_event.php /usr/share/nginx/html/
#COPY pesquisa_eventos.php /usr/share/nginx/html/



